/**
 * The changelog's shape, its filters, and the text the viewer exports.
 *
 * Everything here is pure and synchronous so that the parts worth arguing about - what a date
 * range includes, what an empty result means, what a copied changelog still carries - are
 * testable without mounting anything.
 *
 * The data itself lives in `./changelogData.generated.ts`, which is generated by
 * `scripts/build-changelog.mjs` from this repository's git history and release tags. This file
 * is the authority for the category identifiers: the generated module is typed against
 * {@link ChangelogCategory}, so a category the generator invents and this file cannot label
 * fails the type check rather than reaching a viewer that would render an empty heading.
 *
 * ### Dates are compared as calendar days, in the commit's own offset
 *
 * Every date in the data is a full ISO timestamp with the offset the commit was made in. The
 * filter compares the leading `YYYY-MM-DD` of that string against the day keys the calendar
 * produces, lexicographically. That is deliberate: converting to `Date` and back would move a
 * late-evening commit into the next day for a reader in another timezone, and a changelog that
 * quietly reassigns dates by where it is being read is a changelog that cannot be checked
 * against the repository it describes.
 */

/* -------------------------------------------------------------------------- */
/* Shape                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * The areas an entry can be filed under.
 *
 * Areas, not "added / fixed / changed": the commits in this repository carry no such marker,
 * so classifying them that way would mean inferring intent from a subject line. The area a
 * commit touched is derivable from the paths in the commit itself, which is a fact rather than
 * a reading. `scripts/build-changelog.mjs` holds the same list and the path rules behind it.
 */
export const CHANGELOG_CATEGORIES = [
    "interface",
    "engine",
    "services",
    "shell",
    "site",
    "build",
    "docs",
    "other",
] as const;

export type ChangelogCategory = (typeof CHANGELOG_CATEGORIES)[number];

export interface ChangelogEntry {
    /** The full 40-character SHA, so the entry stays traceable after it is copied. */
    readonly sha: string;
    /** The rendered form of the same commit, unique across the whole changelog. */
    readonly shortSha: string;
    /** The commit's own committer date, ISO 8601 with offset. */
    readonly date: string;
    readonly subject: string;
    /** The commit message body with its trailers removed. May be empty. */
    readonly details: string;
    readonly category: ChangelogCategory;
    /** Every area the commit touched, most-changed first. Always includes `category`. */
    readonly areas: readonly ChangelogCategory[];
    /** How many files the commit changed. */
    readonly files: number;
    /**
     * Set only on a merge commit: how many commits it brought to the mainline.
     *
     * Those commits are listed under the same version alongside it, so this entry is a summary
     * of work that is also recorded individually, and the viewer says so rather than letting
     * the merge look like a change of its own.
     */
    readonly summarizes?: number;
}

export interface ChangelogVersion {
    /** The tag with its leading `v` removed, which is what the release calls itself. */
    readonly version: string;
    readonly tag: string;
    /** The tagged commit's date, ISO 8601 with offset. */
    readonly date: string;
    /** The commit the tag points at. */
    readonly commit: string;
    readonly entries: readonly ChangelogEntry[];
}

/* -------------------------------------------------------------------------- */
/* Links                                                                      */
/* -------------------------------------------------------------------------- */

/**
 * The URL a commit reference resolves to.
 *
 * The base comes from the generated module rather than being written here, so the links point
 * at whichever repository the changelog was generated from instead of at a hard-coded name
 * that would silently be wrong in a fork.
 */
export function commitUrl(repositoryUrl: string, sha: string): string {
    return `${repositoryUrl.replace(/\/+$/, "")}/commit/${sha}`;
}

/* -------------------------------------------------------------------------- */
/* Filtering                                                                  */
/* -------------------------------------------------------------------------- */

/** The `YYYY-MM-DD` of an ISO timestamp, in the offset the timestamp carries. */
export function dayOf(iso: string): string {
    return iso.slice(0, 10);
}

/**
 * What the viewer filters with.
 *
 * `matcher` is the predicate the shared regex engine builds from the search bar, so plain text
 * and regular expressions behave here exactly as they do in every other search surface in this
 * app. `from` and `to` are inclusive day keys, either of which may be null.
 */
export interface ChangelogFilter {
    readonly matcher: (value: string) => boolean;
    readonly from: string | null;
    readonly to: string | null;
    /**
     * True when anything is actually filtering.
     *
     * Passed in rather than inferred, because a predicate cannot be asked whether it is
     * selective. It decides one thing: whether a version that shipped with no changes of its
     * own is still shown. Unfiltered, it is, and it says so, because it is part of the record.
     * Filtered, it is not, because a version with no dates and no text in it cannot have
     * matched a date or a search, and leaving it on screen under a 1999 date range would tell
     * the reader it shipped in 1999.
     */
    readonly active: boolean;
}

/** Everything about an entry that the search bar looks at. */
export function entrySearchText(entry: ChangelogEntry): string {
    return [entry.subject, entry.details, entry.shortSha, entry.sha, dayOf(entry.date)].join("\n");
}

function withinRange(day: string, from: string | null, to: string | null): boolean {
    if (from !== null && day < from) return false;
    if (to !== null && day > to) return false;
    return true;
}

/**
 * True when an entry survives both filters.
 *
 * The two compose rather than override: an entry has to satisfy the date range *and* the
 * search. That is the whole point of having both, and it is also the case that is easy to get
 * wrong by letting a non-empty query bypass the range.
 */
export function entryMatches(entry: ChangelogEntry, filter: ChangelogFilter): boolean {
    if (!withinRange(dayOf(entry.date), filter.from, filter.to)) return false;
    return filter.matcher(entrySearchText(entry));
}

export interface ChangelogSection {
    readonly category: ChangelogCategory;
    readonly entries: readonly ChangelogEntry[];
}

export interface FilteredVersion {
    readonly version: ChangelogVersion;
    readonly sections: readonly ChangelogSection[];
    readonly entries: readonly ChangelogEntry[];
    /**
     * True when this version has no entries of its own at all, filters aside.
     *
     * A tag can land on a commit an earlier tag already covered, which is a version that really
     * did ship with nothing new in it. The viewer says so in those words instead of hiding the
     * version, because a gap in the list reads as a changelog that lost something.
     */
    readonly empty: boolean;
}

export interface FilteredChangelog {
    readonly unreleased: readonly ChangelogSection[];
    readonly unreleasedEntries: readonly ChangelogEntry[];
    readonly versions: readonly FilteredVersion[];
    /** Entries shown, across every version and the unreleased section. */
    readonly shown: number;
    /** Entries in the changelog before either filter ran. */
    readonly total: number;
}

function sectionsOf(entries: readonly ChangelogEntry[]): ChangelogSection[] {
    return CHANGELOG_CATEGORIES.map((category) => ({
        category,
        entries: entries.filter((entry) => entry.category === category),
    })).filter((section) => section.entries.length > 0);
}

/**
 * Applies both filters to the whole changelog.
 *
 * A version whose entries all fail is dropped, because leaving it in with an empty body would
 * be indistinguishable from a version that genuinely shipped no changes, and those two facts
 * must never look the same. A version that really did ship nothing stays while nothing is
 * filtering, and says so in the viewer's own words.
 */
export function filterChangelog(
    versions: readonly ChangelogVersion[],
    unreleased: readonly ChangelogEntry[],
    filter: ChangelogFilter,
): FilteredChangelog {
    const unreleasedEntries = unreleased.filter((entry) => entryMatches(entry, filter));

    const filtered: FilteredVersion[] = [];
    for (const version of versions) {
        const empty = version.entries.length === 0 && !filter.active;
        const entries = version.entries.filter((entry) => entryMatches(entry, filter));
        if (entries.length === 0 && !empty) continue;
        filtered.push({ version, entries, sections: sectionsOf(entries), empty });
    }

    const total =
        unreleased.length + versions.reduce((sum, version) => sum + version.entries.length, 0);
    const shown =
        unreleasedEntries.length + filtered.reduce((sum, version) => sum + version.entries.length, 0);

    return {
        unreleased: sectionsOf(unreleasedEntries),
        unreleasedEntries,
        versions: filtered,
        shown,
        total,
    };
}

/**
 * One line of text per entry, which is what the regex builder previews against.
 *
 * The builder is shown the corpus the search actually runs over, so a pattern that matches in
 * the preview matches in the list. Bodies are folded onto their own lines so a multi-line
 * message does not make one entry look like several.
 */
export function changelogSampleText(
    versions: readonly ChangelogVersion[],
    unreleased: readonly ChangelogEntry[],
): string {
    return [...unreleased, ...versions.flatMap((version) => [...version.entries])]
        .map((entry) => `${entry.shortSha} ${entry.subject}`)
        .join("\n");
}

/* -------------------------------------------------------------------------- */
/* Export                                                                     */
/* -------------------------------------------------------------------------- */

export interface ExportLabels {
    /** The document's own title. */
    readonly title: string;
    /** The line stating which slice of the changelog this file holds. */
    readonly range: string;
    /** Heading for the not-yet-released section. */
    readonly unreleased: string;
    /** Per-category headings, keyed by category id. */
    readonly categories: Readonly<Record<ChangelogCategory, string>>;
    /** Rendered for a version that shipped with nothing recorded against it. */
    readonly noChanges: string;
    /** `{count}` is substituted: what a merge entry summarises. */
    readonly summary: (count: number) => string;
    /** Rendered when the filters left nothing at all. */
    readonly noMatches: string;
}

export interface ExportOptions {
    readonly repositoryUrl: string;
    readonly labels: ExportLabels;
    /** When set, only these SHAs are exported, in changelog order. */
    readonly selection?: ReadonlySet<string>;
}

function selected(
    entries: readonly ChangelogEntry[],
    selection: ReadonlySet<string> | undefined,
): ChangelogEntry[] {
    if (selection === undefined || selection.size === 0) return [...entries];
    return entries.filter((entry) => selection.has(entry.sha));
}

/**
 * The filtered view as Markdown, carrying every SHA in full.
 *
 * The full SHA travels beside the short one because a copied changelog leaves this app: the
 * short form is what a reader scans, and the long form is what still resolves years later in a
 * repository that has grown enough to make ten hex digits ambiguous.
 */
export function toMarkdown(view: FilteredChangelog, options: ExportOptions): string {
    const { labels } = options;
    const lines: string[] = [`# ${labels.title}`, "", labels.range, ""];

    const entryLine = (entry: ChangelogEntry): string => {
        const link = `[\`${entry.shortSha}\`](${commitUrl(options.repositoryUrl, entry.sha)})`;
        const summary = entry.summarizes === undefined ? "" : ` _(${labels.summary(entry.summarizes)})_`;
        return `- ${entry.subject} - ${link}${summary}`;
    };

    const renderSections = (entries: readonly ChangelogEntry[]): string[] => {
        const out: string[] = [];
        for (const section of sectionsOf(entries)) {
            out.push(`### ${labels.categories[section.category]}`, "");
            for (const entry of section.entries) out.push(entryLine(entry));
            out.push("");
        }
        return out;
    };

    let written = 0;

    const unreleased = selected(view.unreleasedEntries, options.selection);
    if (unreleased.length > 0) {
        written += unreleased.length;
        lines.push(`## ${labels.unreleased}`, "", ...renderSections(unreleased));
    }

    for (const filtered of view.versions) {
        const entries = selected(filtered.entries, options.selection);
        if (entries.length === 0 && !(filtered.empty && options.selection === undefined)) continue;
        written += entries.length;
        const version = filtered.version;
        lines.push(
            `## ${version.version} - ${dayOf(version.date)}`,
            "",
            `\`${version.commit}\``,
            "",
        );
        if (entries.length === 0) lines.push(labels.noChanges, "");
        else lines.push(...renderSections(entries));
    }

    if (written === 0) lines.push(labels.noMatches, "");

    return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}

/**
 * The same view as plain text, for somewhere that cannot render Markdown.
 *
 * It carries the same facts, including the full SHA, so the two exports never disagree about
 * what happened. Only the decoration differs.
 */
export function toPlainText(view: FilteredChangelog, options: ExportOptions): string {
    const { labels } = options;
    const lines: string[] = [labels.title, "=".repeat(labels.title.length), "", labels.range, ""];

    const entryLine = (entry: ChangelogEntry): string => {
        const summary = entry.summarizes === undefined ? "" : ` (${labels.summary(entry.summarizes)})`;
        return `  - ${entry.subject} [${entry.sha}]${summary}`;
    };

    const renderSections = (entries: readonly ChangelogEntry[]): string[] => {
        const out: string[] = [];
        for (const section of sectionsOf(entries)) {
            out.push(`  ${labels.categories[section.category]}`);
            for (const entry of section.entries) out.push(entryLine(entry));
            out.push("");
        }
        return out;
    };

    let written = 0;

    const unreleased = selected(view.unreleasedEntries, options.selection);
    if (unreleased.length > 0) {
        written += unreleased.length;
        lines.push(labels.unreleased, "", ...renderSections(unreleased));
    }

    for (const filtered of view.versions) {
        const entries = selected(filtered.entries, options.selection);
        if (entries.length === 0 && !(filtered.empty && options.selection === undefined)) continue;
        written += entries.length;
        const version = filtered.version;
        lines.push(`${version.version}  ${dayOf(version.date)}  ${version.commit}`, "");
        if (entries.length === 0) lines.push(`  ${labels.noChanges}`, "");
        else lines.push(...renderSections(entries));
    }

    if (written === 0) lines.push(labels.noMatches, "");

    return `${lines.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
}
