/**
 * What the screenshot harness points the app at.
 *
 * The capture used to open the app's default profile, which was the public BlueMap demo
 * at bluecolored.de: a server another person maintains as a courtesy. Every push pulled
 * real map tiles off it, so the captures cost somebody else bandwidth, changed with their
 * uptime, and quietly implied this project renders worlds when what they actually proved
 * was the viewer port (issue #17).
 *
 * So the harness serves its own map instead. The map comes from CI: a world generated by
 * `packages/worldgen` (no Minecraft, no server jar, nothing downloaded) and rendered by
 * upstream's BlueMap engine, both in the same run. This module serves that render over
 * loopback and hands the spec a profile pointing at it.
 *
 * ## Served by the product's own handler
 *
 * The fixture server is `LocalMapHandler` behind `HttpServer`, the same pair the app uses
 * for a map it rendered itself. Nothing about the serving rules - `.gz` fallback, 204 for
 * a tile that was never rendered, ETag revalidation - is reimplemented here, so a capture
 * cannot pass against a lenient test double and fail against the real thing.
 *
 * ## Three modes, and they are never confused for each other
 *
 * - `local`  a rendered map is available: served over loopback, captured, captioned as a
 *            viewer capture of a locally rendered world.
 * - `none`   no rendered map reached this run (a fork that declined Mojang's EULA, or a
 *            developer who has not rendered one). The app is captured with no profile at
 *            all, and every caption says the map area is an empty state.
 * - `remote` a real remote BlueMap server, on purpose, from the opt-in job. The caption
 *            names the server and says the tiles are theirs.
 */

import { readFile, readdir, stat } from "node:fs/promises";
import { createHash } from "node:crypto";
import { isAbsolute, join, resolve } from "node:path";
import { HttpServer } from "@worldlens/server";
import type { HttpHandler } from "@worldlens/server";
import { LocalMapHandler } from "../src/main/render/index.js";
import type * as http from "node:http";

/** The mount id the fixture server uses; it only ever serves one map. */
const FIXTURE_RENDER_ID = "capture";

/**
 * What CI records about the map it rendered, written next to the render as
 * `capture-provenance.json`. Every field is optional because a caption must degrade to
 * "we do not know" rather than to a confident invention.
 */
export interface CaptureProvenance {
    /** Human-readable renderer, e.g. "upstream BlueMap Java engine (CLI 5.22-27)". */
    readonly renderer?: string;
    readonly engineVersion?: string;
    readonly mapId?: string;
    readonly mapName?: string;
    readonly world?: {
        readonly seed?: number;
        readonly size?: number;
        readonly chunks?: number;
        readonly versionName?: string;
        readonly dataVersion?: number;
        readonly generator?: string;
        readonly command?: string;
    };
    readonly renderedAt?: string;
    readonly commit?: string;
    readonly run?: string;
    /** The map artifact handed to the viewer, with a digest of its bytes. */
    readonly renderedArtifact?: { readonly path: string; readonly sha256: string };
    /** The viewer identity the render is expected to open. */
    readonly viewer?: { readonly dataRoot: string; readonly mapId: string };
    /** Number of level-0 hires tiles in the rendered artifact. */
    readonly hiresTiles?: number;
    /** Set when no map was rendered, saying why in plain words. */
    readonly unavailable?: string;
}

export interface CaptureProfile {
    readonly id: string;
    readonly name: string;
    readonly url: string;
    readonly trustCustomizations: boolean;
}

export interface CaptureTarget {
    readonly mode: "local" | "remote" | "none";
    /** The profile to seed, or null when there is deliberately no map. */
    readonly profile: CaptureProfile | null;
    /** `#map:x:y:z:...`, so the camera is the same in every run. Empty when unknown. */
    readonly locationHash: string;
    readonly provenance: CaptureProvenance | null;
    /** Facts read from the rendered artifact, never inferred from the caption. */
    readonly renderEvidence: {
        readonly renderedArtifact: { readonly path: string; readonly sha256: string } | null;
        readonly hiresTiles: number | null;
        readonly viewer: { readonly dataRoot: string; readonly mapId: string } | null;
    };
    /** Origins the app is allowed to talk to. Loopback is added by the guard itself. */
    readonly allowedOrigins: string[];
    /** One sentence naming what rendered the map, for every caption. */
    readonly caption: string;
    /** Requests the fixture server answered. Zero in a mode that has no fixture server. */
    servedRequests(): number;
    close(): Promise<void>;
}

/** Counts what the viewer actually asked for, so the manifest can report real numbers. */
class CountingHandler implements HttpHandler {
    private count = 0;

    constructor(private readonly inner: HttpHandler) {}

    get served(): number {
        return this.count;
    }

    async handle(req: http.IncomingMessage, res: http.ServerResponse): Promise<boolean> {
        const handled = await this.inner.handle(req, res);
        if (handled) this.count += 1;
        return handled;
    }
}

/** Reads the current Worldlens variable first and falls back to its read-only legacy alias. */
export function migrationEnvironment(
    values: NodeJS.ProcessEnv,
    currentName: string,
    legacyName: string,
): string | null {
    const current = values[currentName];
    if (current !== undefined && current.trim().length > 0) return current.trim();
    const legacy = values[legacyName];
    return legacy === undefined || legacy.trim().length === 0 ? null : legacy.trim();
}

async function isDirectory(path: string): Promise<boolean> {
    try {
        return (await stat(path)).isDirectory();
    } catch {
        return false;
    }
}

async function readJson<T>(path: string): Promise<T | null> {
    try {
        return JSON.parse(await readFile(path, "utf8")) as T;
    } catch {
        return null;
    }
}

/**
 * The map ids the webapp knows about, read from the render's own `settings.json`.
 *
 * Read rather than assumed: the viewer's location hash starts with a map id, and a hash
 * naming a map that is not there silently falls back to whatever the map's own start
 * position is, which is how a capture ends up pointed at the corner of a world.
 */
async function mapIdsFrom(webRoot: string): Promise<string[]> {
    const settings = await readJson<{ maps?: unknown }>(join(webRoot, "settings.json"));
    if (settings === null || !Array.isArray(settings.maps)) return [];
    return settings.maps.filter((id): id is string => typeof id === "string");
}

/**
 * A camera over the middle of the world.
 *
 * `BlueMapApp.loadPageAddress` reads `#map:x:y:z:distance:rotation:angle:tilt:ortho:state`
 * and the generated world occupies `0..size`, so its centre is `size / 2`. Without this
 * the view starts at `start-pos: { x: 0, z: 0 }`, which for this world is the corner and
 * puts void across most of the frame.
 */
function locationHashFor(mapId: string, size: number | undefined): string {
    if (size === undefined || !Number.isFinite(size) || size <= 0) return `#${mapId}`;
    const centre = Math.round(size / 2);
    const distance = Math.min(1500, Math.max(300, Math.round(size * 0.6)));
    return `#${mapId}:${centre}:63:${centre}:${distance}:0:0.4:0:0:perspective`;
}

function describeWorld(provenance: CaptureProvenance | null): string {
    const world = provenance?.world;
    // No provenance record means the run was pointed at a rendered web root from outside this
    // repository, which is exactly the case this default used to describe wrongly: it claimed
    // "a world this repository generated" for a world the repository has never seen. Every
    // capture in the committed gallery carried that sentence after the harness was first run
    // against a real save, including the one the README leads with.
    //
    // What is actually known without a provenance file is that somebody handed the run a
    // rendered map, so that is what this says. Naming the absence is the whole point of the
    // caption: a reader who needs to know which world it was can be told it is not recorded,
    // and a reader who is told a false origin cannot know to ask.
    if (world === undefined) {
        return "a world rendered outside this repository and supplied to the capture run, whose origin this run has no record of";
    }
    const parts: string[] = [];
    if (world.seed !== undefined) parts.push(`seed ${world.seed}`);
    if (world.size !== undefined) parts.push(`${world.size}x${world.size} blocks`);
    if (world.versionName !== undefined) parts.push(`Minecraft ${world.versionName}`);
    const detail = parts.length === 0 ? "" : ` (${parts.join(", ")})`;
    return `a synthetic world this repository generated${detail}`;
}

/**
 * The caption every published image carries.
 *
 * The point of it is the third defect in issue #17: a screenshot of a fully rendered
 * world invites the reading that this project renders worlds. It does not yet. So the
 * caption names the renderer, and says outright that the TypeScript mesher rendered none
 * of what is on screen.
 */
function captionFor(
    mode: CaptureTarget["mode"],
    provenance: CaptureProvenance | null,
    remoteUrl: string | null,
): string {
    if (mode === "remote") {
        return (
            `Real Electron app, remote mode, browsing ${remoteUrl ?? "a remote BlueMap server"}. ` +
            "The tiles belong to that server and were rendered by whoever runs it. This capture " +
            "comes from a job that is started by hand, not from a push. It proves the viewer " +
            "port, the reverse proxy and the token-gated embedded server, and nothing about " +
            "rendering."
        );
    }
    if (mode === "none") {
        const why = provenance?.unavailable ?? "no rendered map reached this run";
        return (
            "Real Electron app with no map loaded: " +
            why +
            ". The map area is the app's empty state, not a rendering failure. Nothing was " +
            "fetched from any network."
        );
    }
    const renderer = provenance?.renderer ?? "upstream BlueMap's Java engine";
    return (
        `Real Electron app. The map was rendered by ${renderer} from ${describeWorld(provenance)}, ` +
        "and is served to the app over loopback by this repository's own map handler. What it " +
        "proves is the viewer port, the embedded server and the reverse proxy. The TypeScript " +
        "mesher in packages/engine rendered none of it."
    );
}

function noTarget(caption: string, provenance: CaptureProvenance | null): CaptureTarget {
    return {
        mode: "none",
        profile: null,
        locationHash: "",
        provenance,
        renderEvidence: { renderedArtifact: null, hiresTiles: null, viewer: null },
        allowedOrigins: [],
        caption,
        servedRequests: () => 0,
        close: () => Promise.resolve(),
    };
}

async function countHiresTiles(webRoot: string, mapId: string): Promise<number> {
    const root = join(webRoot, "maps", mapId, "tiles", "0");
    let total = 0;
    async function walk(path: string): Promise<void> {
        let entries;
        try {
            entries = await readdir(path, { withFileTypes: true });
        } catch {
            return;
        }
        for (const entry of entries) {
            const child = join(path, entry.name);
            if (entry.isDirectory()) await walk(child);
            else if (/\.prbm(?:\.gz)?$/u.test(entry.name)) total += 1;
        }
    }
    await walk(root);
    return total;
}

async function hashTree(root: string): Promise<string> {
    const entries: Array<[string, Buffer]> = [];
    const walk = async (directory: string, prefix = ""): Promise<void> => {
        for (const entry of await readdir(directory, { withFileTypes: true })) {
            const child = join(directory, entry.name);
            const relativePath = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
            if (entry.isDirectory()) await walk(child, relativePath);
            else if (entry.isFile()) entries.push([relativePath, await readFile(child)]);
        }
    };
    await walk(root);
    entries.sort(([a], [b]) => a.localeCompare(b));
    const hash = createHash("sha256");
    for (const [name, bytes] of entries) hash.update(name).update("\0").update(bytes);
    return hash.digest("hex");
}

/**
 * Resolves and starts whatever this run is capturing.
 *
 * `WORLDLENS_CAPTURE_MODE`       `local` (default) or `remote`
 * `WORLDLENS_CAPTURE_MAP`        local: the rendered web root (settings.json + maps/)
 * `WORLDLENS_CAPTURE_PROVENANCE` local: the JSON CI wrote about that render
 * `WORLDLENS_CAPTURE_REMOTE_URL` remote: the server to browse
 *
 * The former `MATERIAL_BLUEMAP_CAPTURE_*` names remain read-only aliases. Current names
 * always win when both generations are present.
 *
 * A missing or unusable local map is not an error. It produces the `none` mode, which
 * captures the app honestly rather than quietly falling back to somebody's public server.
 */
export async function resolveCaptureTarget(): Promise<CaptureTarget> {
    const mode =
        migrationEnvironment(
            process.env,
            "WORLDLENS_CAPTURE_MODE",
            "MATERIAL_BLUEMAP_CAPTURE_MODE",
        ) ?? "local";

    if (mode === "remote") {
        const url = migrationEnvironment(
            process.env,
            "WORLDLENS_CAPTURE_REMOTE_URL",
            "MATERIAL_BLUEMAP_CAPTURE_REMOTE_URL",
        );
        if (url === null) {
            throw new Error(
                "WORLDLENS_CAPTURE_MODE=remote needs WORLDLENS_CAPTURE_REMOTE_URL. " +
                    "Remote captures name the server they browsed; there is no default.",
            );
        }
        const origin = new URL(url).origin;
        return {
            mode: "remote",
            profile: {
                id: "capture-remote",
                name: `Remote capture (${origin})`,
                url,
                trustCustomizations: false,
            },
            locationHash: "",
            provenance: null,
            allowedOrigins: [origin],
            caption: captionFor("remote", null, url),
            servedRequests: () => 0,
            close: () => Promise.resolve(),
        };
    }

    if (mode !== "local") {
        throw new Error(`Unknown WORLDLENS_CAPTURE_MODE '${mode}'; use 'local' or 'remote'.`);
    }

    const rawRoot = migrationEnvironment(
        process.env,
        "WORLDLENS_CAPTURE_MAP",
        "MATERIAL_BLUEMAP_CAPTURE_MAP",
    );
    const provenancePath = migrationEnvironment(
        process.env,
        "WORLDLENS_CAPTURE_PROVENANCE",
        "MATERIAL_BLUEMAP_CAPTURE_PROVENANCE",
    );
    const webRoot = rawRoot === null ? null : isAbsolute(rawRoot) ? rawRoot : resolve(rawRoot);

    let provenance: CaptureProvenance | null =
        provenancePath === null ? null : await readJson<CaptureProvenance>(provenancePath);

    if (webRoot === null) {
        provenance ??= {
            unavailable:
                "WORLDLENS_CAPTURE_MAP was not set, so this run had no rendered map to serve",
        };
        return noTarget(captionFor("none", provenance, null), provenance);
    }

    if (provenance === null) {
        provenance =
            (await readJson<CaptureProvenance>(join(webRoot, "capture-provenance.json"))) ??
            (await readJson<CaptureProvenance>(resolve(webRoot, "..", "capture-provenance.json")));
    }

    if (!(await isDirectory(webRoot))) {
        const unavailable = `the capture map directory ${webRoot} does not exist`;
        return noTarget(captionFor("none", { unavailable }, null), provenance ?? { unavailable });
    }

    const mapIds = await mapIdsFrom(webRoot);
    if (mapIds.length === 0) {
        const unavailable = `${webRoot} has no webapp settings.json listing any map, so there is nothing to serve`;
        return noTarget(captionFor("none", { unavailable }, null), provenance ?? { unavailable });
    }

    const handler = new LocalMapHandler();
    handler.setMount({
        renderId: FIXTURE_RENDER_ID,
        webRoot,
        engineLabel: provenance?.renderer ?? "unrecorded renderer",
    });
    const counting = new CountingHandler(handler);

    // Port 0: the operating system picks a free one, so two runs on one machine never
    // collide and no fixed port has to be reserved anywhere.
    const server = new HttpServer({ host: "127.0.0.1", port: 0 });
    server.addHandler(counting);
    const address = await server.listen();
    const baseUrl = `http://127.0.0.1:${address.port}${LocalMapHandler.dataRoot(FIXTURE_RENDER_ID)}`;

    const mapId = provenance?.mapId ?? mapIds[0]!;
    const hiresTiles = await countHiresTiles(webRoot, mapId);
    if (provenance?.hiresTiles !== undefined && provenance.hiresTiles !== hiresTiles) {
        throw new Error(
            `capture provenance says ${String(provenance.hiresTiles)} hires tiles, but the rendered artifact contains ${String(hiresTiles)}`,
        );
    }
    if (provenance?.viewer !== undefined && provenance.viewer.mapId !== mapId) {
        throw new Error(
            `capture provenance names viewer map '${provenance.viewer.mapId}', but settings.json names '${mapId}'`,
        );
    }
    const viewer = provenance?.viewer ?? { dataRoot: LocalMapHandler.dataRoot(FIXTURE_RENDER_ID), mapId };
    const computedArtifact = {
        path: webRoot,
        sha256: await hashTree(webRoot),
    };
    if (
        provenance?.renderedArtifact !== undefined &&
        provenance.renderedArtifact.sha256 !== computedArtifact.sha256
    ) {
        throw new Error("capture provenance rendered-artifact digest does not match the artifact served to the viewer");
    }
    const renderedArtifact = provenance?.renderedArtifact ?? computedArtifact;
    return {
        mode: "local",
        profile: {
            id: "capture-local",
            name: provenance?.mapName ?? "Locally rendered test world",
            url: baseUrl,
            trustCustomizations: false,
        },
        locationHash: locationHashFor(mapId, provenance?.world?.size),
        provenance,
        renderEvidence: {
            renderedArtifact,
            hiresTiles,
            viewer,
        },
        allowedOrigins: [new URL(baseUrl).origin],
        caption: captionFor("local", provenance, null),
        servedRequests: () => counting.served,
        close: () => server.close(),
    };
}
