/**
 * Deterministic size planning for repository-backed world snapshots.
 *
 * GitHub's public ceiling is higher, but Worldlens deliberately keeps every generated
 * commit and every transmitted Git pack below decimal 1.5 GB. Planning stops at 1.4 GB so
 * trees, commit objects and pack framing have room; the caller still measures the objects
 * generated for every candidate commit and refuses anything over the hard ceilings.
 */

/** Decimal 1.5 GB, intentionally not 1.5 GiB. */
export const WORLD_REPO_MAX_INTRODUCED_BYTES = 1_500_000_000;

/** Decimal 1.5 GB for the Git pack generated by one push. */
export const WORLD_REPO_MAX_PUSH_BYTES = 1_500_000_000;

/** Raw-file planning target, leaving 100 MB for Git metadata and pack framing. */
export const WORLD_REPO_PLANNING_TARGET_BYTES = 1_400_000_000;

/**
 * A deliberately conservative per-path allowance for tree entries and object headers.
 * The exact generated objects are measured after each commit; this keeps ordinary plans
 * comfortably below the point where that final hard check would need to refuse them.
 */
export const WORLD_REPO_PATH_OVERHEAD_BYTES = 256;

export interface WorldRepoBatchFile {
    readonly path: string;
    readonly bytes: number;
}

export interface WorldRepoBatchPlan {
    readonly index: number;
    readonly files: readonly WorldRepoBatchFile[];
    readonly sourceBytes: number;
    readonly planningBytes: number;
}

/** UTF-8 byte order is stable across operating systems and locale settings. */
export function compareWorldRepoPaths(left: string, right: string): number {
    return Buffer.compare(Buffer.from(left, "utf8"), Buffer.from(right, "utf8"));
}

/**
 * Splits a snapshot by deterministic path order and a conservative byte budget.
 *
 * The optional target exists so focused tests can exercise many batches without creating
 * gigabytes of fixtures. It may only lower the production target, never raise it.
 */
export function planWorldRepoBatches(
    input: readonly WorldRepoBatchFile[],
    requestedTargetBytes = WORLD_REPO_PLANNING_TARGET_BYTES,
): readonly WorldRepoBatchPlan[] {
    if (!Number.isSafeInteger(requestedTargetBytes) || requestedTargetBytes <= 0) {
        throw new RangeError("The world repository batch target must be a positive safe integer.");
    }
    const targetBytes = Math.min(requestedTargetBytes, WORLD_REPO_PLANNING_TARGET_BYTES);
    const files = [...input].sort((left, right) => compareWorldRepoPaths(left.path, right.path));
    const batches: WorldRepoBatchPlan[] = [];
    let current: WorldRepoBatchFile[] = [];
    let sourceBytes = 0;
    let planningBytes = 0;

    const finish = (): void => {
        if (current.length === 0 && batches.length > 0) return;
        batches.push({ index: batches.length, files: current, sourceBytes, planningBytes });
        current = [];
        sourceBytes = 0;
        planningBytes = 0;
    };

    for (const file of files) {
        if (!Number.isSafeInteger(file.bytes) || file.bytes < 0) {
            throw new RangeError(`${file.path} has an invalid byte size.`);
        }
        const weight =
            file.bytes + Buffer.byteLength(file.path, "utf8") + WORLD_REPO_PATH_OVERHEAD_BYTES;
        if (weight > WORLD_REPO_MAX_INTRODUCED_BYTES) {
            throw new RangeError(`${file.path} cannot fit in one bounded world repository commit.`);
        }
        if (current.length > 0 && planningBytes + weight > targetBytes) finish();
        current.push(file);
        sourceBytes += file.bytes;
        planningBytes += weight;
    }
    finish();
    return batches;
}

/**
 * A conservative upper bound for a no-delta Git pack containing the given object bodies.
 *
 * `compressBound` is reproduced from zlib's documented bound, then padded for each pack
 * entry header and a SHA-256 trailer. The actual repository may use SHA-1, whose trailer is
 * smaller. WorldRepo configures pushes without delta/object reuse so the transmitted object
 * set cannot grow hidden bases beyond the set measured by the caller.
 */
export function gitPackUpperBound(objectSizes: readonly number[]): number {
    let total = 12 + 32;
    for (const size of objectSizes) {
        if (!Number.isSafeInteger(size) || size < 0)
            throw new RangeError("Invalid Git object size.");
        const compressedBound =
            size +
            Math.ceil(size / 4_096) +
            Math.ceil(size / 16_384) +
            Math.ceil(size / 33_554_432) +
            13;
        total += compressedBound + 16;
    }
    return total;
}
