export {
    SCREENSHOT_EVIDENCE_ROOTS,
    createScreenshotGallery,
    isGalleryAssetBasename,
    isEvidenceAssetPath,
    type GalleryAction,
    type GalleryExport,
    type GalleryAssetInspector,
    type GalleryRevision,
    type GalleryState,
    type GalleryStorage,
    type ScreenshotCamera,
    type ScreenshotDimensions,
    type ScreenshotDraft,
    type ScreenshotMetadata,
    type ScreenshotProvenance,
    type ScreenshotRecord,
    type ScreenshotSearch,
    type ScreenshotAssetInput,
    type ScreenshotUpdate,
} from "./screenshotGalleryModel.js";
