#!/usr/bin/env node
/**
 * When each committed screenshot was taken, and how old that makes it.
 *
 * A gallery without dates asks the reader to trust that the pictures are current, which is
 * exactly the thing they cannot check. This writes one small record - `docs/screenshots/
 * capture-dates.json` - naming, for every committed capture, the moment it was taken and where
 * that moment came from.
 *
 * ## Two sources, never blended silently
 *
 * The harness stamps `capturedAt` on each entry it writes to `manifest.json`, and that is the
 * exact truth: the instant the shutter closed. Captures committed before the harness recorded
 * that stamp have no such field, so their date is taken from git - the commit that last changed
 * the file - and labelled `committed` rather than `captured`. The two are different claims and
 * the record says which one each file carries, because a date presented as the capture time when
 * it is really the commit time is the kind of small lie that makes a whole gallery untrustworthy.
 *
 * ## Why no "how long ago" is written here
 *
 * Relative ages are computed where they are displayed, never stored. A committed file saying
 * "3 days ago" is wrong on the fourth day and wrong forever after; the site computes the age in
 * the reader's browser from the absolute timestamp, so it is right every time it is read. The
 * only relative figure this script prints is on stdout, for the person running it.
 *
 *   node scripts/screenshot-dates.mjs           # write the record
 *   node scripts/screenshot-dates.mjs --check   # fail if it is out of date
 */

import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const SHOTS = join(REPO_ROOT, "docs", "screenshots");
const MANIFEST = join(SHOTS, "manifest.json");
const OUTPUT = join(SHOTS, "capture-dates.json");

/** ISO-8601 with the seconds kept and the milliseconds dropped: stable, and precise enough. */
function normaliseInstant(value) {
    const parsed = new Date(value);
    if (Number.isNaN(parsed.getTime())) return null;
    return `${parsed.toISOString().slice(0, 19)}Z`;
}

function harnessStamps() {
    const stamps = new Map();
    let manifest;
    try {
        manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
    } catch {
        return stamps;
    }
    for (const capture of manifest.captures ?? []) {
        if (typeof capture.file !== "string") continue;
        const at = typeof capture.capturedAt === "string" ? normaliseInstant(capture.capturedAt) : null;
        if (at !== null) stamps.set(capture.file, at);
    }
    return stamps;
}

/**
 * The commit that last changed this file, as an instant.
 *
 * One `git log` per file is slower than one batched call, and it is what keeps this honest: a
 * batched `--name-only` walk attributes a file to whichever commit mentioned it, and a rename or
 * a mode change would then date a picture by an event that never touched its pixels.
 */
function committedInstant(file) {
    const output = execFileSync(
        "git",
        ["log", "-1", "--format=%cI", "--", join("docs", "screenshots", file)],
        { cwd: REPO_ROOT, encoding: "utf8", maxBuffer: 8 * 1024 * 1024 },
    ).trim();
    return output === "" ? null : normaliseInstant(output);
}

/** A plain-language age. Whole units only, because "1.7 months" is not how anyone speaks. */
export function humanAge(fromIso, nowMs) {
    const then = new Date(fromIso).getTime();
    if (Number.isNaN(then)) return "an unknown time ago";
    const seconds = Math.max(0, Math.round((nowMs - then) / 1000));
    const units = [
        ["year", 31_536_000],
        ["month", 2_592_000],
        ["week", 604_800],
        ["day", 86_400],
        ["hour", 3_600],
        ["minute", 60],
    ];
    for (const [name, size] of units) {
        const count = Math.floor(seconds / size);
        if (count >= 1) return `${count} ${name}${count === 1 ? "" : "s"} ago`;
    }
    return "just now";
}

function build() {
    const stamps = harnessStamps();
    const files = readdirSync(SHOTS)
        .filter((name) => name.toLowerCase().endsWith(".png"))
        .sort();
    const entries = {};
    for (const file of files) {
        const captured = stamps.get(file) ?? null;
        const at = captured ?? committedInstant(file);
        if (at === null) continue;
        entries[file] = { at, source: captured === null ? "committed" : "captured" };
    }
    return { note: "Generated by scripts/screenshot-dates.mjs. Ages are computed where they are shown, never stored.", entries };
}

function main(argv) {
    const record = build();
    const text = `${JSON.stringify(record, null, 4)}\n`;
    if (argv.includes("--check")) {
        let current = "";
        try {
            current = readFileSync(OUTPUT, "utf8");
        } catch {
            current = "";
        }
        if (current.replace(/\r\n/g, "\n") !== text) {
            console.error(
                "screenshot-dates: docs/screenshots/capture-dates.json is out of date. Run `node scripts/screenshot-dates.mjs` and commit the result.",
            );
            process.exit(1);
        }
        console.log(`screenshot-dates: ${Object.keys(record.entries).length} captures dated, record is current`);
        return;
    }
    writeFileSync(OUTPUT, text, "utf8");
    const now = Date.now();
    const ages = Object.entries(record.entries).map(([file, entry]) => `${file} ${entry.at} (${humanAge(entry.at, now)}, ${entry.source})`);
    console.log(`screenshot-dates: wrote ${ages.length} dated captures`);
    for (const line of ages.slice(0, 3)) console.log(`  ${line}`);
    if (ages.length > 3) console.log(`  ... and ${ages.length - 3} more`);
}

if (process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`) {
    main(process.argv.slice(2));
}
