/**
 * `webapp.conf` — what the web viewer is built with and how it behaves.
 *
 * Java source: `common/src/main/java/de/bluecolored/bluemap/common/config/WebappConfig.java`
 * Template:    `common/src/main/resources/de/bluecolored/bluemap/config/webapp.conf`
 */

import { z } from "zod";
import type { FieldMeta, GroupMeta } from "../meta.js";
import { WEBAPP_TEMPLATE } from "../templates/sources.js";
import { hoconBoolean, hoconInt, hoconNumber, hoconString, integerControl, RESOLUTION_OPTIONS, SWITCH } from "./common.js";
import type { ConfigFileDescriptor } from "./descriptor.js";

/** A Java `LinkedHashSet<String>`: ordered, and duplicates collapse. */
function uniqueStringList(): z.ZodType<string[]> {
    return z.preprocess(
        (value) => (Array.isArray(value) ? Array.from(new Set(value.map((item) => (typeof item === "number" || typeof item === "boolean" ? String(item) : item)))) : value),
        z.array(z.string()),
    );
}

export const webappConfigSchema = z.object({
    enabled: hoconBoolean().default(true),
    webroot: hoconString().default("bluemap/web"),
    "update-settings-file": hoconBoolean().default(true),
    "use-cookies": hoconBoolean().default(true),
    "default-to-flat-view": hoconBoolean().default(false),
    "start-location": hoconString().nullable().default(null),
    "min-zoom-distance": hoconInt().default(5),
    "max-zoom-distance": hoconInt().default(100000),
    "resolution-default": hoconNumber().default(1),
    "hires-slider-max": hoconInt().default(500),
    "hires-slider-default": hoconInt().default(100),
    "hires-slider-min": hoconInt().default(0),
    "lowres-slider-max": hoconInt().default(7000),
    "lowres-slider-default": hoconInt().default(2000),
    "lowres-slider-min": hoconInt().default(500),
    "map-data-root": hoconString().default("maps"),
    "live-data-root": hoconString().default("maps"),
    "client-decompression": hoconBoolean().default(false),
    scripts: uniqueStringList().default([]),
    styles: uniqueStringList().default([]),
});

export type WebappConfig = z.infer<typeof webappConfigSchema>;

const GROUPS: readonly GroupMeta[] = [
    { id: "general", label: "Web app" },
    { id: "startup", label: "What a visitor sees first" },
    { id: "camera", label: "Camera limits" },
    { id: "sliders", label: "Render distance sliders" },
    { id: "hosting", label: "Where data is loaded from" },
    { id: "custom", label: "Custom scripts and styles" },
];

const ZOOM_DOC = [
    "The minimum (closest) and maximum (furthest) distance (in blocks) that the camera can be from the ground.",
    "Default is min:5 max:100000",
].join("\n");

const HIRES_SLIDER_DOC = [
    "The min, max and default values of the hires render distance slider (settings menu).",
    "The values are in blocks.",
    "Default is max:500 default:100 and min:0",
].join("\n");

const LOWRES_SLIDER_DOC = [
    "The min, max and default values of the lowres render distance slider (settings menu).",
    "The values are in blocks.",
    "Default is max:7000 default:2000 and min:500",
].join("\n");

const FIELDS: readonly FieldMeta[] = [
    {
        path: "enabled",
        key: "enabled",
        segments: ["enabled"],
        javaField: "enabled",
        label: "Create and update the web app",
        doc: ["With this setting you can disable the creation and updating of all webapp related files.", "Default is true"].join("\n"),
        group: "general",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "webroot",
        key: "webroot",
        segments: ["webroot"],
        javaField: "webroot",
        label: "Web root",
        doc: [
            "The webroot where the webapp files will be created.",
            "Usually this should be set to the same directory like in the webserver.conf!",
            'Default is "bluemap/web"',
        ].join("\n"),
        group: "general",
        control: { kind: "path", select: "directory", relativeToWorkingDirectory: true },
        default: "bluemap/web",
        templateValue: { value: "web", note: "The CLI passes 'web' as its default web root, so a generated webapp.conf says web rather than bluemap/web." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "update-settings-file",
        key: "update-settings-file",
        segments: ["update-settings-file"],
        javaField: "updateSettingsFile",
        label: "Keep settings.json in sync",
        doc: [
            'Whether the settings.json of the webapp should be updated/synchronized with the current BlueMap settings.',
            'If this is set to "false", BlueMap will only add maps to the settings.json but never remove unknown ones or update other settings.',
            "Disabling this is for example useful if you are running multiple BlueMap instances on the same webroot and don't want them to overwrite each others maps.",
            "Default is true",
        ].join("\n"),
        group: "general",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "use-cookies",
        key: "use-cookies",
        segments: ["use-cookies"],
        javaField: "useCookies",
        label: "Remember viewer settings in cookies",
        doc: ["If the webapp should use cookies to save the configurations of a user.", "Default is true"].join("\n"),
        group: "general",
        control: SWITCH,
        default: true,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "default-to-flat-view",
        key: "default-to-flat-view",
        segments: ["default-to-flat-view"],
        javaField: "defaultToFlatView",
        label: "Open in flat view",
        doc: ["If the webapp will default to flat-view instead of perspective-view.", "Default is false (perspective-view)"].join("\n"),
        group: "startup",
        control: SWITCH,
        default: false,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "start-location",
        key: "start-location",
        segments: ["start-location"],
        javaField: "startLocation",
        label: "Start location",
        doc: [
            "The default map and camera location where a user will start after opening the webapp.",
            "This is in form of the URL anchor: Open your map in a browser and look at the URL, everything after the '#' is the value for this setting.",
            'Default is "no anchor" (The camera will start with the topmost map and at that map\'s starting point).',
        ].join("\n"),
        group: "startup",
        control: { kind: "text", monospace: true, placeholder: "world:0:16:-32:390:0.1:0.19:0:0:perspective" },
        default: null,
        commentedOutInTemplate: true,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "min-zoom-distance",
        key: "min-zoom-distance",
        segments: ["min-zoom-distance"],
        javaField: "minZoomDistance",
        label: "Closest camera distance",
        doc: ZOOM_DOC,
        group: "camera",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 5,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "max-zoom-distance",
        key: "max-zoom-distance",
        segments: ["max-zoom-distance"],
        javaField: "maxZoomDistance",
        label: "Furthest camera distance",
        doc: ZOOM_DOC,
        group: "camera",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 100000,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "resolution-default",
        key: "resolution-default",
        segments: ["resolution-default"],
        javaField: "resolutionDefault",
        label: "Default resolution",
        doc: ["The default value of the resolution (settings menu).", "Possible values are: 0.5, 1, 2", "Default is 1"].join("\n"),
        group: "startup",
        // Upstream lists three values and the Java field is a plain `float`, so a
        // hand-written 1.5 loads perfectly well. A closed select bound to 1.5 would
        // render empty, which reads as "this setting is unset" and is overwritten by
        // the next click. Free entry keeps the file's own value visible.
        control: { kind: "select", allowCustom: true, options: RESOLUTION_OPTIONS },
        default: 1,
        advisory: { oneOf: [0.5, 1, 2], note: "Upstream documents 0.5, 1 and 2. Another value is passed through to the viewer untouched, so it may or may not do anything useful." },
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "hires-slider-max",
        key: "hires-slider-max",
        segments: ["hires-slider-max"],
        javaField: "hiresSliderMax",
        label: "Hires slider maximum",
        doc: HIRES_SLIDER_DOC,
        group: "sliders",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 500,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "hires-slider-default",
        key: "hires-slider-default",
        segments: ["hires-slider-default"],
        javaField: "hiresSliderDefault",
        label: "Hires slider default",
        doc: HIRES_SLIDER_DOC,
        group: "sliders",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 100,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "hires-slider-min",
        key: "hires-slider-min",
        segments: ["hires-slider-min"],
        javaField: "hiresSliderMin",
        label: "Hires slider minimum",
        doc: HIRES_SLIDER_DOC,
        group: "sliders",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 0,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "lowres-slider-max",
        key: "lowres-slider-max",
        segments: ["lowres-slider-max"],
        javaField: "lowresSliderMax",
        label: "Lowres slider maximum",
        doc: LOWRES_SLIDER_DOC,
        group: "sliders",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 7000,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "lowres-slider-default",
        key: "lowres-slider-default",
        segments: ["lowres-slider-default"],
        javaField: "lowresSliderDefault",
        label: "Lowres slider default",
        doc: LOWRES_SLIDER_DOC,
        group: "sliders",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 2000,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "lowres-slider-min",
        key: "lowres-slider-min",
        segments: ["lowres-slider-min"],
        javaField: "lowresSliderMin",
        label: "Lowres slider minimum",
        doc: LOWRES_SLIDER_DOC,
        group: "sliders",
        control: integerControl({ min: 0, step: 1, unit: "blocks" }),
        default: 500,
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: false,
    },
    {
        path: "map-data-root",
        key: "map-data-root",
        segments: ["map-data-root"],
        javaField: "mapDataRoot",
        label: "Map data base URL",
        doc: ["Here you can specify an alternative base URL where all of the map data is loaded from.", 'Default is "maps"'].join("\n"),
        group: "hosting",
        control: { kind: "text", monospace: true, placeholder: "https://cdn.my-domain.com/mapdata" },
        default: "maps",
        commentedOutInTemplate: true,
        hidden: false,
        invalidatesTiles: false,
        advanced: true,
    },
    {
        path: "live-data-root",
        key: "live-data-root",
        segments: ["live-data-root"],
        javaField: "liveDataRoot",
        label: "Live data base URL",
        doc: ["Here you can specify an alternative base URL where all of the live data is loaded from.", 'Default is "maps"'].join("\n"),
        group: "hosting",
        control: { kind: "text", monospace: true, placeholder: "https://cdn.my-domain.com/livedata" },
        default: "maps",
        commentedOutInTemplate: true,
        hidden: false,
        invalidatesTiles: false,
        advanced: true,
    },
    {
        path: "client-decompression",
        key: "client-decompression",
        segments: ["client-decompression"],
        javaField: "clientDecompression",
        label: "Decompress map tiles in the browser",
        doc: [
            "This will configure the webapp to request the map-tiles compressed and decompress them manually.",
            "Enable this only if you intend to host the webapp statically, with an external webserver without additional configuration.",
            'Default is "false"',
        ].join("\n"),
        group: "hosting",
        control: SWITCH,
        default: false,
        commentedOutInTemplate: true,
        hidden: false,
        invalidatesTiles: false,
        advanced: true,
    },
    {
        path: "scripts",
        key: "scripts",
        segments: ["scripts"],
        javaField: "scripts",
        label: "Custom scripts",
        doc: [
            "Here you can add URLs to custom scripts (js) so they will be loaded by the webapp.",
            "You can place them somewhere in BlueMap's webroot and add the (relative) link here.",
        ].join("\n"),
        group: "custom",
        control: { kind: "list", itemLabel: "Script URL", unique: true, item: { kind: "text", monospace: true, placeholder: "js/my-custom-script.js" } },
        default: [],
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: true,
    },
    {
        path: "styles",
        key: "styles",
        segments: ["styles"],
        javaField: "styles",
        label: "Custom styles",
        doc: [
            "Here you can add URLs to custom styles (css) so they will be loaded by the webapp.",
            "You can place them somewhere in BlueMap's webroot and add the (relative) link here.",
        ].join("\n"),
        group: "custom",
        control: { kind: "list", itemLabel: "Stylesheet URL", unique: true, item: { kind: "text", monospace: true, placeholder: "css/my-custom-style.css" } },
        default: [],
        commentedOutInTemplate: false,
        hidden: false,
        invalidatesTiles: false,
        advanced: true,
    },
];

export const webappConfigDescriptor: ConfigFileDescriptor<WebappConfig> = {
    id: "webapp",
    title: "Web app",
    description: "How the web viewer is generated and what a visitor sees when it opens.",
    location: { pattern: "webapp.conf", cardinality: "single" },
    schema: webappConfigSchema,
    fields: FIELDS,
    groups: GROUPS,
    legacyKeys: [],
    template: WEBAPP_TEMPLATE,
};
