/**
 * Curated real Minecraft Java Edition identifier lists used by the command builder's
 * searchable pickers.
 *
 * HONESTY NOTE (read before trusting or extending this file): these lists were written from
 * this project's own knowledge of the stable, long-standing vanilla Java Edition registries
 * (effects, enchantments, particles, sounds, attributes, gamerules, dimensions, difficulties,
 * gamemodes, scoreboard criteria, entity type ids used by /summon). They were NOT fetched or
 * cross-checked against a specific game version's generated data reports in this session - no
 * network access or bundled version manifest was available while this file was written. They
 * are a practical, curated subset believed accurate for modern Java Edition releases, not a
 * complete or version-pinned dump of every id (for example, item and block registries run into
 * the thousands and are not enumerated here at all).
 *
 * Every picker built from these lists is a combo box: choosing a listed id is the easy path,
 * but typing any other id the game accepts is always available too, because these lists can
 * never be exhaustive and must never block a command that is otherwise valid. Advancement ids
 * are not listed at all - they are datapack- and version-specific to a degree these other
 * categories are not, so that picker is free-entry only. See CommandBuilder.vue and the task
 * report for the full list of which categories are curated vs. free-entry-only.
 */

export const ITEM_IDS = [
    "minecraft:diamond",
    "minecraft:diamond_sword",
    "minecraft:diamond_pickaxe",
    "minecraft:diamond_axe",
    "minecraft:diamond_shovel",
    "minecraft:diamond_hoe",
    "minecraft:diamond_helmet",
    "minecraft:diamond_chestplate",
    "minecraft:diamond_leggings",
    "minecraft:diamond_boots",
    "minecraft:netherite_ingot",
    "minecraft:netherite_sword",
    "minecraft:iron_ingot",
    "minecraft:iron_sword",
    "minecraft:iron_pickaxe",
    "minecraft:golden_apple",
    "minecraft:enchanted_golden_apple",
    "minecraft:apple",
    "minecraft:bread",
    "minecraft:cooked_beef",
    "minecraft:golden_carrot",
    "minecraft:emerald",
    "minecraft:gold_ingot",
    "minecraft:stick",
    "minecraft:bow",
    "minecraft:arrow",
    "minecraft:crossbow",
    "minecraft:shield",
    "minecraft:totem_of_undying",
    "minecraft:elytra",
    "minecraft:ender_pearl",
    "minecraft:ender_eye",
    "minecraft:experience_bottle",
    "minecraft:potion",
    "minecraft:splash_potion",
    "minecraft:lingering_potion",
    "minecraft:tipped_arrow",
    "minecraft:name_tag",
    "minecraft:lead",
    "minecraft:saddle",
    "minecraft:water_bucket",
    "minecraft:lava_bucket",
    "minecraft:bucket",
    "minecraft:torch",
    "minecraft:chest",
    "minecraft:crafting_table",
    "minecraft:furnace",
    "minecraft:anvil",
    "minecraft:enchanting_table",
    "minecraft:book",
    "minecraft:enchanted_book",
    "minecraft:writable_book",
    "minecraft:written_book",
    "minecraft:map",
    "minecraft:filled_map",
    "minecraft:compass",
    "minecraft:clock",
    "minecraft:spyglass",
    "minecraft:flint_and_steel",
    "minecraft:shears",
    "minecraft:fishing_rod",
    "minecraft:tnt",
    "minecraft:redstone",
    "minecraft:string",
    "minecraft:paper",
    "minecraft:leather",
    "minecraft:oak_log",
    "minecraft:oak_planks",
    "minecraft:cobblestone",
    "minecraft:stone",
    "minecraft:dirt",
    "minecraft:grass_block",
    "minecraft:sand",
    "minecraft:gravel",
    "minecraft:obsidian",
    "minecraft:glass",
    "minecraft:wool",
    "minecraft:netherite_helmet",
    "minecraft:turtle_helmet",
    "minecraft:trident",
    "minecraft:firework_rocket",
    "minecraft:firework_star",
    "minecraft:music_disc_cat",
    "minecraft:player_head",
] as const;

export const BLOCK_IDS = [
    "minecraft:air",
    "minecraft:stone",
    "minecraft:granite",
    "minecraft:diorite",
    "minecraft:andesite",
    "minecraft:deepslate",
    "minecraft:cobblestone",
    "minecraft:dirt",
    "minecraft:grass_block",
    "minecraft:podzol",
    "minecraft:sand",
    "minecraft:red_sand",
    "minecraft:gravel",
    "minecraft:oak_log",
    "minecraft:oak_planks",
    "minecraft:oak_leaves",
    "minecraft:glass",
    "minecraft:obsidian",
    "minecraft:bedrock",
    "minecraft:water",
    "minecraft:lava",
    "minecraft:netherrack",
    "minecraft:soul_sand",
    "minecraft:soul_soil",
    "minecraft:glowstone",
    "minecraft:end_stone",
    "minecraft:diamond_block",
    "minecraft:emerald_block",
    "minecraft:gold_block",
    "minecraft:iron_block",
    "minecraft:netherite_block",
    "minecraft:redstone_block",
    "minecraft:tnt",
    "minecraft:chest",
    "minecraft:crafting_table",
    "minecraft:furnace",
    "minecraft:bookshelf",
    "minecraft:torch",
    "minecraft:sea_lantern",
    "minecraft:wool",
    "minecraft:barrier",
    "minecraft:structure_void",
    "minecraft:command_block",
    "minecraft:repeating_command_block",
    "minecraft:chain_command_block",
    "minecraft:spawner",
    "minecraft:beacon",
    "minecraft:bedrock",
    "minecraft:snow_block",
    "minecraft:ice",
    "minecraft:packed_ice",
    "minecraft:blue_ice",
    "minecraft:magma_block",
    "minecraft:crying_obsidian",
    "minecraft:respawn_anchor",
    "minecraft:lodestone",
] as const;

export const ENTITY_TYPE_IDS = [
    "minecraft:zombie",
    "minecraft:skeleton",
    "minecraft:creeper",
    "minecraft:spider",
    "minecraft:enderman",
    "minecraft:witch",
    "minecraft:slime",
    "minecraft:magma_cube",
    "minecraft:blaze",
    "minecraft:ghast",
    "minecraft:wither_skeleton",
    "minecraft:phantom",
    "minecraft:drowned",
    "minecraft:husk",
    "minecraft:stray",
    "minecraft:pillager",
    "minecraft:vindicator",
    "minecraft:evoker",
    "minecraft:ravager",
    "minecraft:vex",
    "minecraft:guardian",
    "minecraft:elder_guardian",
    "minecraft:shulker",
    "minecraft:silverfish",
    "minecraft:endermite",
    "minecraft:piglin",
    "minecraft:piglin_brute",
    "minecraft:hoglin",
    "minecraft:zoglin",
    "minecraft:wither",
    "minecraft:ender_dragon",
    "minecraft:warden",
    "minecraft:villager",
    "minecraft:wandering_trader",
    "minecraft:cow",
    "minecraft:pig",
    "minecraft:sheep",
    "minecraft:chicken",
    "minecraft:horse",
    "minecraft:donkey",
    "minecraft:mule",
    "minecraft:llama",
    "minecraft:cat",
    "minecraft:wolf",
    "minecraft:fox",
    "minecraft:rabbit",
    "minecraft:bee",
    "minecraft:turtle",
    "minecraft:panda",
    "minecraft:polar_bear",
    "minecraft:dolphin",
    "minecraft:squid",
    "minecraft:glow_squid",
    "minecraft:cod",
    "minecraft:salmon",
    "minecraft:tropical_fish",
    "minecraft:pufferfish",
    "minecraft:bat",
    "minecraft:parrot",
    "minecraft:allay",
    "minecraft:axolotl",
    "minecraft:goat",
    "minecraft:frog",
    "minecraft:tadpole",
    "minecraft:camel",
    "minecraft:sniffer",
    "minecraft:armor_stand",
    "minecraft:item",
    "minecraft:experience_orb",
    "minecraft:tnt",
    "minecraft:falling_block",
    "minecraft:arrow",
    "minecraft:fireball",
    "minecraft:lightning_bolt",
    "minecraft:boat",
    "minecraft:minecart",
    "minecraft:painting",
    "minecraft:item_frame",
    "minecraft:end_crystal",
] as const;

export const EFFECT_IDS = [
    "minecraft:speed",
    "minecraft:slowness",
    "minecraft:haste",
    "minecraft:mining_fatigue",
    "minecraft:strength",
    "minecraft:instant_health",
    "minecraft:instant_damage",
    "minecraft:jump_boost",
    "minecraft:nausea",
    "minecraft:regeneration",
    "minecraft:resistance",
    "minecraft:fire_resistance",
    "minecraft:water_breathing",
    "minecraft:invisibility",
    "minecraft:blindness",
    "minecraft:night_vision",
    "minecraft:hunger",
    "minecraft:weakness",
    "minecraft:poison",
    "minecraft:wither",
    "minecraft:health_boost",
    "minecraft:absorption",
    "minecraft:saturation",
    "minecraft:glowing",
    "minecraft:levitation",
    "minecraft:luck",
    "minecraft:unluck",
    "minecraft:slow_falling",
    "minecraft:conduit_power",
    "minecraft:dolphins_grace",
    "minecraft:bad_omen",
    "minecraft:hero_of_the_village",
    "minecraft:darkness",
    "minecraft:infested",
    "minecraft:oozing",
    "minecraft:weaving",
    "minecraft:wind_charged",
] as const;

export const ENCHANTMENT_IDS = [
    "minecraft:protection",
    "minecraft:fire_protection",
    "minecraft:feather_falling",
    "minecraft:blast_protection",
    "minecraft:projectile_protection",
    "minecraft:respiration",
    "minecraft:aqua_affinity",
    "minecraft:thorns",
    "minecraft:depth_strider",
    "minecraft:frost_walker",
    "minecraft:binding_curse",
    "minecraft:soul_speed",
    "minecraft:swift_sneak",
    "minecraft:sharpness",
    "minecraft:smite",
    "minecraft:bane_of_arthropods",
    "minecraft:knockback",
    "minecraft:fire_aspect",
    "minecraft:looting",
    "minecraft:sweeping_edge",
    "minecraft:efficiency",
    "minecraft:silk_touch",
    "minecraft:unbreaking",
    "minecraft:fortune",
    "minecraft:power",
    "minecraft:punch",
    "minecraft:flame",
    "minecraft:infinity",
    "minecraft:luck_of_the_sea",
    "minecraft:lure",
    "minecraft:loyalty",
    "minecraft:impaling",
    "minecraft:riptide",
    "minecraft:channeling",
    "minecraft:multishot",
    "minecraft:quick_charge",
    "minecraft:piercing",
    "minecraft:density",
    "minecraft:breach",
    "minecraft:wind_burst",
    "minecraft:mending",
    "minecraft:vanishing_curse",
] as const;

export const PARTICLE_IDS = [
    "minecraft:flame",
    "minecraft:smoke",
    "minecraft:large_smoke",
    "minecraft:campfire_cosy_smoke",
    "minecraft:explosion",
    "minecraft:huge_explosion_emitter",
    "minecraft:heart",
    "minecraft:crit",
    "minecraft:enchant",
    "minecraft:portal",
    "minecraft:reverse_portal",
    "minecraft:dragon_breath",
    "minecraft:end_rod",
    "minecraft:soul",
    "minecraft:soul_fire_flame",
    "minecraft:cloud",
    "minecraft:note",
    "minecraft:witch",
    "minecraft:splash",
    "minecraft:bubble",
    "minecraft:fireworks_spark",
    "minecraft:totem_of_undying",
    "minecraft:composter",
    "minecraft:happy_villager",
    "minecraft:angry_villager",
    "minecraft:snowflake",
    "minecraft:dust",
    "minecraft:falling_dust",
    "minecraft:ash",
    "minecraft:glow",
    "minecraft:sonic_boom",
] as const;

export const SOUND_IDS = [
    "minecraft:entity.experience_orb.pickup",
    "minecraft:entity.player.levelup",
    "minecraft:entity.ender_dragon.growl",
    "minecraft:entity.wither.spawn",
    "minecraft:entity.enderman.teleport",
    "minecraft:entity.firework_rocket.blast",
    "minecraft:entity.generic.explode",
    "minecraft:entity.villager.yes",
    "minecraft:entity.villager.no",
    "minecraft:entity.cat.purr",
    "minecraft:entity.wolf.howl",
    "minecraft:block.note_block.pling",
    "minecraft:block.anvil.land",
    "minecraft:block.chest.open",
    "minecraft:block.chest.close",
    "minecraft:block.beacon.activate",
    "minecraft:block.portal.travel",
    "minecraft:ui.button.click",
    "minecraft:music.game",
    "minecraft:music.creative",
    "minecraft:music.nether.basalt_deltas",
    "minecraft:ambient.cave",
    "minecraft:weather.rain",
    "minecraft:entity.lightning_bolt.thunder",
] as const;

export const ATTRIBUTE_IDS = [
    "minecraft:generic.max_health",
    "minecraft:generic.follow_range",
    "minecraft:generic.knockback_resistance",
    "minecraft:generic.movement_speed",
    "minecraft:generic.flying_speed",
    "minecraft:generic.attack_damage",
    "minecraft:generic.attack_knockback",
    "minecraft:generic.attack_speed",
    "minecraft:generic.armor",
    "minecraft:generic.armor_toughness",
    "minecraft:generic.luck",
    "minecraft:generic.max_absorption",
    "minecraft:generic.safe_fall_distance",
    "minecraft:generic.fall_damage_multiplier",
    "minecraft:generic.gravity",
    "minecraft:generic.jump_strength",
    "minecraft:generic.scale",
    "minecraft:generic.step_height",
    "minecraft:generic.burning_time",
    "minecraft:generic.explosion_knockback_resistance",
    "minecraft:generic.movement_efficiency",
    "minecraft:generic.oxygen_bonus",
    "minecraft:generic.water_movement_efficiency",
    "minecraft:zombie.spawn_reinforcements",
    "minecraft:horse.jump_strength",
] as const;

export const GAMERULE_IDS = [
    "doDaylightCycle",
    "doWeatherCycle",
    "doMobSpawning",
    "doMobLoot",
    "doTileDrops",
    "doEntityDrops",
    "doFireTick",
    "mobGriefing",
    "keepInventory",
    "naturalRegeneration",
    "randomTickSpeed",
    "reducedDebugInfo",
    "sendCommandFeedback",
    "showDeathMessages",
    "spawnRadius",
    "spectatorsGenerateChunks",
    "commandBlockOutput",
    "logAdminCommands",
    "disableElytraMovementCheck",
    "maxEntityCramming",
    "doInsomnia",
    "doImmediateRespawn",
    "drowningDamage",
    "fallDamage",
    "fireDamage",
    "freezeDamage",
    "doPatrolSpawning",
    "doTraderSpawning",
    "doWardenSpawning",
    "forgiveDeadPlayers",
    "universalAnger",
    "playersSleepingPercentage",
    "maxCommandChainLength",
    "announceAdvancements",
    "disableRaids",
    "doLimitedCrafting",
    "fallDamageMultiplier",
] as const;

export const GAMEMODES = ["survival", "creative", "adventure", "spectator"] as const;
export const DIFFICULTIES = ["peaceful", "easy", "normal", "hard"] as const;
export const WEATHER_TYPES = ["clear", "rain", "thunder"] as const;
export const FILL_MODES = ["replace", "keep", "outline", "hollow", "destroy"] as const;
export const CLONE_MODES = ["force", "move", "normal"] as const;
export const CLONE_MASK_MODES = ["replace", "masked", "filtered"] as const;
export const XP_UNITS = ["points", "levels"] as const;
export const TITLE_SLOTS = ["title", "subtitle", "actionbar", "clear", "reset", "times"] as const;
export const SCOREBOARD_CRITERIA = [
    "dummy",
    "trigger",
    "health",
    "xp",
    "level",
    "food",
    "air",
    "armor",
    "deathCount",
    "playerKillCount",
    "totalKillCount",
] as const;
export const SELECTOR_SORTS = ["nearest", "furthest", "random", "arbitrary"] as const;
export const LOCATE_KINDS = ["structure", "biome", "poi"] as const;
export const DATA_TARGET_KINDS = ["block", "entity", "storage"] as const;
export const EXECUTE_CLAUSE_KINDS = [
    "as",
    "at",
    "positioned",
    "rotated",
    "facing",
    "align",
    "anchored",
    "in",
    "if",
    "unless",
    "store",
] as const;
