/**
 * Hand-written `FieldMeta` for `velocity.toml`, the Velocity proxy's own configuration
 * file.
 *
 * Velocity is a proxy, not a server flavour that owns a world - `server.properties` never
 * applies to it, and this is its entire configuration surface. Bounds, defaults and
 * comments are taken from the config template PaperMC's Velocity ships and documents at
 * `docs.papermc.io/velocity/configuration` (config-version `2.7`, the shape used by every
 * Velocity 3.x release at the time this was written).
 *
 * Two keys deliberately stay out of this schema rather than being faked:
 * `servers` (the backend-server name/address map) and `forced-hosts` (the hostname/backend
 * map) are both open-ended tables the operator grows freely - there is no fixed field list
 * to declare, and each existing entry still reaches the GUI as an inferred field through
 * `describe.ts`'s no-schema fallback instead of a text box. `servers.try` is a real ordered
 * list of server names and is modelled as one.
 */

import type { FieldMeta } from "@worldlens/config";
import { boundedInt, field, ms, port, select, text } from "./schemaHelpers.js";

export const velocityFields: readonly FieldMeta[] = [
    field({
        path: "config-version",
        label: "Config version",
        doc: "Do not change this. It tells Velocity which config file version this is, so it can upgrade an old file automatically.",
        control: { kind: "text" },
        default: "2.7",
        advanced: true,
    }),
    field({
        path: "bind",
        label: "Bind address",
        doc: "What host and port should the proxy bind to? By default, this is 0.0.0.0:25577, which means it will listen on all interfaces.",
        control: { kind: "text", monospace: true },
        default: "0.0.0.0:25577",
    }),
    field({
        path: "motd",
        label: "MOTD",
        doc: "What should be the MOTD? This gets displayed when the player adds your server to their server list. Legacy color codes and MiniMessage formatting are accepted.",
        control: text(true),
        default: "<#09add3>A Velocity Server",
    }),
    field({
        path: "show-max-players",
        label: "Shown max players",
        doc: "What should we display for the maximum number of players? (Velocity does not support a cap on the number of players online.)",
        control: boundedInt(1, 2147483647, "players"),
        default: 500,
    }),
    field({
        path: "online-mode",
        label: "Online mode",
        doc: "Should we authenticate players with Mojang? By default, this is on.",
        control: { kind: "switch" },
        default: true,
    }),
    field({
        path: "force-key-authentication",
        label: "Force key authentication",
        doc: "Should we forward messages signed key authentication? This is required for chat signing to work, and by default, this is on. Disabling this will also disable Message Signing.",
        control: { kind: "switch" },
        default: true,
        advanced: true,
    }),
    field({
        path: "prevent-client-proxy-connections",
        label: "Prevent client proxy connections",
        doc: "If client's ISP/AS sent from this proxy is different from the one from Mojang's authentication server, the player is kicked.",
        control: { kind: "switch" },
        default: false,
    }),
    field({
        path: "player-info-forwarding-mode",
        label: "Player info forwarding mode",
        doc: "Should Velocity attempt to gracefully handle situations where a server may be listed as being requested twice? This is called player-info-forwarding-mode; it can be NONE, LEGACY, BUNGEEGUARD or MODERN.",
        control: select(
            [
                { value: "NONE", label: "None" },
                { value: "LEGACY", label: "Legacy" },
                { value: "BUNGEEGUARD", label: "BungeeGuard" },
                { value: "MODERN", label: "Modern" },
            ],
            true,
        ),
        default: "MODERN",
    }),
    field({
        path: "forwarding-secret-file",
        label: "Forwarding secret file",
        doc: "Path to the file containing the forwarding secret, used by modern and BungeeGuard forwarding.",
        control: { kind: "path", select: "file", relativeToWorkingDirectory: true },
        default: "forwarding.secret",
        advanced: true,
    }),
    field({
        path: "announce-forge",
        label: "Announce Forge",
        doc: "Announce whether or not your server supports Forge/FML. If you run a modded server, we suggest turning this on.",
        control: { kind: "switch" },
        default: false,
    }),
    field({
        path: "kick-existing-players",
        label: "Kick existing players",
        doc: "If your server is in offline mode, should we kick any existing players that are online when using online mode?",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
    field({
        path: "ping-passthrough",
        label: "Ping passthrough",
        doc: "Should Velocity pass server list ping requests to the backend server? Options are DISABLED, MODS, DESCRIPTION, and ALL.",
        control: select(
            [
                { value: "DISABLED", label: "Disabled" },
                { value: "MODS", label: "Mods" },
                { value: "DESCRIPTION", label: "Description" },
                { value: "ALL", label: "All" },
            ],
            true,
        ),
        default: "DISABLED",
        advanced: true,
    }),
    field({
        path: "sample-players-in-ping",
        label: "Sample players in ping",
        doc: "Should Velocity add sample players to the server ping? This is disabled by default.",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
    field({
        path: "enable-player-address-logging",
        label: "Enable player address logging",
        doc: "By default, Velocity will present a fake IP address of 127.0.0.1 for a connecting player to a backend server (relying only on the forwarding protocol for IP forwarding) as a precaution against player IP address leakage. This setting turns off this precaution, but it may have security implications.",
        control: { kind: "switch" },
        default: true,
        advanced: true,
    }),
    field({
        path: "servers.try",
        segments: ["servers", "try"],
        label: "Try servers",
        doc: "In what order should we try connecting players to backend servers? This can be adjusted in-game with the /server command if the player has access to it.",
        control: { kind: "list", item: { kind: "text" }, itemLabel: "Server name", unique: true },
        default: ["lobby"],
    }),
    field({
        path: "advanced.compression-threshold",
        segments: ["advanced", "compression-threshold"],
        label: "Compression threshold",
        doc: "How large a packet has to be before we compress it. Setting this to -1 will disable compression entirely.",
        control: { kind: "number", integer: true, min: -1, unit: "bytes" },
        default: 256,
        advanced: true,
    }),
    field({
        path: "advanced.compression-level",
        segments: ["advanced", "compression-level"],
        label: "Compression level",
        doc: "How much compression should be done (from 0-9). The default is -1, which uses the default level of 6.",
        control: { kind: "number", integer: true, min: -1, max: 9 },
        default: -1,
        advanced: true,
    }),
    field({
        path: "advanced.login-ratelimit",
        segments: ["advanced", "login-ratelimit"],
        label: "Login rate limit",
        doc: "How fast (in milliseconds) are clients allowed to connect after the last connection? By default, this is three seconds. Disable this by setting this to 0.",
        control: ms(0),
        default: 3000,
        advanced: true,
    }),
    field({
        path: "advanced.connection-timeout",
        segments: ["advanced", "connection-timeout"],
        label: "Connection timeout",
        doc: "How long, in milliseconds, should connections wait before being disconnected when attempting to connect to the server?",
        control: ms(0),
        default: 5000,
        advanced: true,
    }),
    field({
        path: "advanced.read-timeout",
        segments: ["advanced", "read-timeout"],
        label: "Read timeout",
        doc: "How long, in milliseconds, should be waited before an authentication request is considered unsuccessful.",
        control: ms(0),
        default: 30000,
        advanced: true,
    }),
    field({
        path: "advanced.haproxy-protocol",
        segments: ["advanced", "haproxy-protocol"],
        label: "HAProxy protocol",
        doc: "Enables compatibility with HAProxy's PROXY protocol. If you don't know what this is, then don't enable it.",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
    field({
        path: "advanced.tcp-fast-open",
        segments: ["advanced", "tcp-fast-open"],
        label: "TCP fast open",
        doc: "Enables TCP fast open support on the proxy. Requires the proxy to run on Linux.",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
    field({
        path: "advanced.bungee-plugin-message-channel",
        segments: ["advanced", "bungee-plugin-message-channel"],
        label: "BungeeCord plugin message channel",
        doc: "Enables the BungeeCord plugin messaging channel, mostly used to support plugins made for BungeeCord.",
        control: { kind: "switch" },
        default: true,
        advanced: true,
    }),
    field({
        path: "advanced.show-ping-requests",
        segments: ["advanced", "show-ping-requests"],
        label: "Show ping requests",
        doc: "Shows ping requests to the proxy in the log.",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
    field({
        path: "advanced.failover-on-unexpected-server-disconnect",
        segments: ["advanced", "failover-on-unexpected-server-disconnect"],
        label: "Failover on unexpected disconnect",
        doc: "Try to gracefully handle player disconnections if they happen as a part of the server switch, e.g. lobby balancing.",
        control: { kind: "switch" },
        default: true,
        advanced: true,
    }),
    field({
        path: "advanced.announce-proxy-commands",
        segments: ["advanced", "announce-proxy-commands"],
        label: "Announce proxy commands",
        doc: "Announce whether or not your server supports the client-side view of proxy commands.",
        control: { kind: "switch" },
        default: true,
        advanced: true,
    }),
    field({
        path: "advanced.log-command-executions",
        segments: ["advanced", "log-command-executions"],
        label: "Log command executions",
        doc: "Log all commands executed by players, including their arguments, in the proxy log.",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
    field({
        path: "advanced.log-player-connections",
        segments: ["advanced", "log-player-connections"],
        label: "Log player connections",
        doc: "Logs player connections/disconnections to the proxy log.",
        control: { kind: "switch" },
        default: true,
        advanced: true,
    }),
    field({
        path: "advanced.accepts-transfers",
        segments: ["advanced", "accepts-transfers"],
        label: "Accepts transfers",
        doc: "Allows players transferred from other hosts via the modern 1.20.5+ transfer packet to be transferred to this proxy.",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
    field({
        path: "query.enabled",
        segments: ["query", "enabled"],
        label: "Enable query",
        doc: "Whether to enable the GameSpy 4 query protocol or not.",
        control: { kind: "switch" },
        default: false,
    }),
    field({
        path: "query.port",
        segments: ["query", "port"],
        label: "Query port",
        doc: "If query is enabled, on what port should the query protocol listen on?",
        control: port(),
        default: 25577,
    }),
    field({
        path: "query.map",
        segments: ["query", "map"],
        label: "Query map name",
        doc: "This is the map name that is reported to the query services.",
        control: text(),
        default: "Velocity",
        advanced: true,
    }),
    field({
        path: "query.show-plugins",
        segments: ["query", "show-plugins"],
        label: "Show plugins in query",
        doc: "Whether plugins should be shown in query response by default or not.",
        control: { kind: "switch" },
        default: false,
        advanced: true,
    }),
];
